### PR TITLE
Add resource type as 2nd param in decode method

### PR DESCRIPTION
**Pull request by win0err**
It's a minor clarification of input parameters in `JWT::decode` method. 
Second parameter (key) accepts arrays, strings and resources, but in PHPDoc resource type is not listed.

Let's take a look at an example:
```php
<?php

$pubkey =<<<PUBKEY
-----BEGIN PUBLIC KEY-----
[...]
-----END PUBLIC KEY-----
PUBKEY;

$publicKey = openssl_pkey_get_public(pubkey); // $publicKey is a resource
$decodedToken = JWT::decode($token, $publicKey, ['RS256']);
```

If I run static analysis with PHPStan, I will get the following error:
```
Parameter #2 $key of static method Firebase\JWT\JWT::decode() expects array|string, resource given.
```

### CODE REVIEW

**Comment by win0err** [comment]
I signed it!

**Comment by esbobkov** [comment]
Anybody, merge please

**Comment by win0err** [comment]
I've updated PR and resolved conflicts. @bshaffer, please, take a look

**Comment by bshaffer** [comment]
This is great, thanks! And we got it merged in just under 2 years!

**Pull request merged**
