### PR TITLE
chore: fix RS256 example in README

### PR DESCRIPTION
**Pull request by akshaykhale1992**
I tried using the example from README.md, and the JWT Token is getting generated and decoded properly but when I try to verify the generated toke on JWT.io, it shows an error saying **Invalid Signature**.

Here is the [JWT.io link](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLm9yZyIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNjc0ODAxMDk5LCJuYmYiOjE2NzQ4MDQ2OTl9.LZoiHKsmcABUO9BHreRU72NkRhCayqiqMs7yBPHJ-wJiz4jh-DfcD0GkDiuK16wMaihnxHAyX-DsVhMLlrY1ToX00xKZkNIkceRu4sAwDa4j7Yd1EakL_ln3UDdwaCv-f822pfvV21-wY2rqctuf-s87Wz3YLHcNHLwGqBEic0k&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC8kGa1pSjbSYZVebtTRBLxBz5H%0A4i2p%2FllLCrEeQhta5kaQu%2FRnvuER4W8oDH3%2B3iuIYW4VQAzyqFpwuzjkDI%2B17t5t%0A0tyazyZ8JXw%2BKgXTxldMPEL95%2BqVhgXvwtihXC1c5oGbRlEDvDF6Sa53rcFVsYJ4%0Aehde%2FzUxo6UvS7UrBQIDAQAB%0A-----END%20PUBLIC%20KEY-----).

This PR fixes that issue by updating the Private and Public Key-pair generated using openssl

Here is [JWT.io link](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLm9yZyIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.fm0h0Ec3yp7S3JNBLeFa2owu4a91IXFJs8NPgBUxgKKSfd_-Mqes2zxuxmkYpmQDG936u739mIDZyG9KQm0ER5HB243MVbFZHcaC7VAIqmoCZ4dcS6yoJ1ltH6vdwc8o3xkYVEWKvLr8a7ck21u-pASWB_tpqM7XtIu7xyCZhfpmxTbhNyTgsJ1HN4fVYrHn2535qYsetOTps_zM2cgVRQYbkp1RovL-ZDsp3rMxzEiGQ7F80JXh2fsTHKlpPqAyF40GEXvCZa0MIoRa7g1pIjRtNLYgOgO94YsSRGB0VDDsLNdXzkjv0Ujfk_uqtD0IKgt7ffQzh8b8dUl8onXA_g&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzWHNM5f%2BamCjQztc5QT%0AfJfzCC5J4nuW%2BL%2FaOxZ4f8J3FrewM2c%2FdufrnmedsApb0By7WhaHlcqCh%2FScAPyJ%0AhzkPYLae7bTVro3hok0zDITR8F6SJGL42JAEUk%2BILkPI%2BDONM0%2B3vzk6Kvfe548t%0Au4czCuqU8BGVOlnp6IqBHhAswNMM78pos%2F2z0CjPM4tbeXqSTTbNkXRboxjU29vS%0AopcT51koWOgiTf3C7nJUoMWZHZI5HqnIhPAG9yv8HAgNk6CMk2CadVHDo4IxjxTz%0ATTqo1SCSH2pooJl9O8at6kkRYsrZWwsKlOFE2LUce7ObnXsYihStBUDoeBQlGG%2FB%0AwQIDAQAB%0A-----END%20PUBLIC%20KEY-----) after implementing the README fixes.

Best.

### CODE REVIEW

**Comment by bshaffer** [comment]
I'm not sure why exactly, but something is different in `mb_string_split` that is causing all our tests to fail

**Comment by SoulPancake** [comment]
@akshaykhale1992 I had faced this same issue previously, Can you please sign the CLA so the checks can proceed

**Comment by akshaykhale1992** [comment]
Hi @SoulPancake,

I have signed the CLA, please approve the workflow.

Best.

**Review by SoulPancake — APPROVED** [review]
LGTM

**Comment by bshaffer** [comment]
@akshaykhale1992 Thank you for this! However I'm a bit confused... are you saying this library is verifying JWTs that are invalid?

**Comment by akshaykhale1992** [comment]
Hi @bshaffer,

No, there is no issue with the library, What I am trying to say here is that the example in the readme is not getting verified on JWT.io.

The example in the readme is generating the Token and verifying it correctly with the cod but the same token when we check on jwt.io, it's showing an error message saying invalid signature.

Sample Link: [Invalid Signature on JWT.io](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLm9yZyIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxNjc0ODAxMDk5LCJuYmYiOjE2NzQ4MDQ2OTl9.LZoiHKsmcABUO9BHreRU72NkRhCayqiqMs7yBPHJ-wJiz4jh-DfcD0GkDiuK16wMaihnxHAyX-DsVhMLlrY1ToX00xKZkNIkceRu4sAwDa4j7Yd1EakL_ln3UDdwaCv-f822pfvV21-wY2rqctuf-s87Wz3YLHcNHLwGqBEic0k&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQC8kGa1pSjbSYZVebtTRBLxBz5H%0A4i2p%2FllLCrEeQhta5kaQu%2FRnvuER4W8oDH3%2B3iuIYW4VQAzyqFpwuzjkDI%2B17t5t%0A0tyazyZ8JXw%2BKgXTxldMPEL95%2BqVhgXvwtihXC1c5oGbRlEDvDF6Sa53rcFVsYJ4%0Aehde%2FzUxo6UvS7UrBQIDAQAB%0A-----END%20PUBLIC%20KEY-----)

which is due to the Signing Keys in the read me file, I simply updated the example to make sure that we are getting an error-free response on JWT.io.

Sample Link: [Valid Signature on JWT.io](https://jwt.io/#debugger-io?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJleGFtcGxlLm9yZyIsImF1ZCI6ImV4YW1wbGUuY29tIiwiaWF0IjoxMzU2OTk5NTI0LCJuYmYiOjEzNTcwMDAwMDB9.fm0h0Ec3yp7S3JNBLeFa2owu4a91IXFJs8NPgBUxgKKSfd_-Mqes2zxuxmkYpmQDG936u739mIDZyG9KQm0ER5HB243MVbFZHcaC7VAIqmoCZ4dcS6yoJ1ltH6vdwc8o3xkYVEWKvLr8a7ck21u-pASWB_tpqM7XtIu7xyCZhfpmxTbhNyTgsJ1HN4fVYrHn2535qYsetOTps_zM2cgVRQYbkp1RovL-ZDsp3rMxzEiGQ7F80JXh2fsTHKlpPqAyF40GEXvCZa0MIoRa7g1pIjRtNLYgOgO94YsSRGB0VDDsLNdXzkjv0Ujfk_uqtD0IKgt7ffQzh8b8dUl8onXA_g&publicKey=-----BEGIN%20PUBLIC%20KEY-----%0AMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuzWHNM5f%2BamCjQztc5QT%0AfJfzCC5J4nuW%2BL%2FaOxZ4f8J3FrewM2c%2FdufrnmedsApb0By7WhaHlcqCh%2FScAPyJ%0AhzkPYLae7bTVro3hok0zDITR8F6SJGL42JAEUk%2BILkPI%2BDONM0%2B3vzk6Kvfe548t%0Au4czCuqU8BGVOlnp6IqBHhAswNMM78pos%2F2z0CjPM4tbeXqSTTbNkXRboxjU29vS%0AopcT51koWOgiTf3C7nJUoMWZHZI5HqnIhPAG9yv8HAgNk6CMk2CadVHDo4IxjxTz%0ATTqo1SCSH2pooJl9O8at6kkRYsrZWwsKlOFE2LUce7ObnXsYihStBUDoeBQlGG%2FB%0AwQIDAQAB%0A-----END%20PUBLIC%20KEY-----)

The MR modifies nothing but the readme file.

Best.

**Comment by Krisell** [comment]
It's not very clear on `jwt.io`, but I think the reason the original example no longer works is that 2048 bits is the lowest recommended RSA key size. I found this code on `jwt.io`

image

**Review by bshaffer — APPROVED** [review]

**Comment by bshaffer** [comment]
@Krisell thank you for answering my question!

**Pull request merged**
