### PR TITLE
Added Token expiration time when thrown exception.

### PR DESCRIPTION
**Pull request by FilipeVoges**
Added feature so that when the Token expired exception is thrown, it can also be picked up from when the token is expired.

### CODE REVIEW

**Comment by cottton** [comment]
I recommend to NOT merge this commit.
The construct should (if not must) be compatible with parents.
See (all the way through the parent down) `\Exception`
`public __construct ([ string $message = "" [, int $code = 0 [, Throwable $previous = NULL ]]] )`

I suggest to use a setter or a 4th parameter in the construct.
_I would prefer a setter_

**Comment by FilipeVoges** [comment]
> I recommend to NOT merge this commit.
> The construct should (if not must) be compatible with parents.
> See (all the way through the parent down) `\Exception`
> `public __construct ([ string $message = "" [, int $code = 0 [, Throwable $previous = NULL ]]] )`
> 
> I suggest to use a setter or a 4th parameter in the construct.
> _I would prefer a setter_

I will fix this, thanks for the suggestion

**Comment by FilipeVoges** [comment]
> I recommend to NOT merge this commit.
> The construct should (if not must) be compatible with parents.
> See (all the way through the parent down) `\Exception`
> `public __construct ([ string $message = "" [, int $code = 0 [, Throwable $previous = NULL ]]] )`
> 
> I suggest to use a setter or a 4th parameter in the construct.
> _I would prefer a setter_

Adjustment implemented as suggested

**Comment by FilipeVoges** [comment]
> I recommend to NOT merge this commit.
> The construct should (if not must) be compatible with parents.
> See (all the way through the parent down) `\Exception`
> `public __construct ([ string $message = "" [, int $code = 0 [, Throwable $previous = NULL ]]] )`
> 
> I suggest to use a setter or a 4th parameter in the construct.
> _I would prefer a setter_

Adjustment implemented as suggested

**Comment by bshaffer** [comment]
I'm not sure this is useful, so closing it

**Pull request closed without merging**
