### PR TITLE
feat: Add ES256 support to JWK

### PR DESCRIPTION
**Pull request by bshaffer**
See #339

Adds support for parsing `EC256` JWKs

You can test this branch by running the following command:

```
composer require firebase/php-jwt:dev-add-ec-jwk-support
```

Then in your code, use as you normally would:

```php
$jwk = ["keys": [["kty" => "EC","use" => "sig","crv" => "P-256", "kid" => "jwk1", "x": => "abc..", "y" => "xyz..", "alg" => "ES256"]]];
$keys = JWK::parseKeySet($jwk);
$decoded = JWT::decode($ecJwt, $keys);
```

### CODE REVIEW

**Comment by glen-84** [comment]
Could this be backported to 6.0.x?

**Comment by bshaffer** [comment]
@glen-84 What is your use-case? You'd like to see this supported in a version <= PHP 7.1?

**Comment by dunglas** [comment]
I tested this branch while implement [Solid Client PHP](https://github.com/dunglas/solid-client-php) and it worked as expected.

See also https://github.com/jumbojett/OpenID-Connect-PHP/issues/287.

**Comment by glen-84** [comment]
@bshaffer,

> @glen-84 What is your use-case? You'd like to see this supported in a version <= PHP 7.1?

Ya, we're currently stuck on PHP 7.0 for a while.

**Comment by ivaxer** [comment]
@bshaffer Could you tell me please why this PR is not merged? Can I help?

BTW, looks like there is a typo in the title: ES256 -> EC256.

**Pull request merged**
