### PR TITLE
[v6.0] Use array short syntax (introduced in php 5.4)

### PR DESCRIPTION
**Pull request by Krisell**
I updated the code to use the short array syntax which is much more common today and more familiar to developers new to the language. This requires php 5.4 which is why I tagged this for v6.0.

### CODE REVIEW

**Comment by Krisell** [comment]
A note about the failing Travis tests: It's only php version 5.3 that fails, which is expected as mentioned above.

**Comment by bshaffer** [comment]
Thank you! This seems fine to introduce for `v6.0`, I agree. We should also drop support in `.travis.yaml` For PHP <= 7.1 (at least) as well.

**Comment by bshaffer** [comment]
I am now thinking there's no reason for us to drop support for EOL versions of PHP unless there is a good reason, and this PR only requires us drop support for PHP 5.3.

**Comment by bshaffer** [comment]
Closing as short array syntax is not a priority

**Pull request closed without merging**
