### PR TITLE
adds option to decode to an associative array

### PR DESCRIPTION
**Pull request by csfalcione**

### CODE REVIEW

**Comment by cfalcione** [comment]
Made this before seeing https://github.com/firebase/php-jwt/issues/30

**Comment by bshaffer** [comment]
Closing as a stdclass can be cast to an array in PHP easily

```sh
php > $std = new StdClass;
php > $std->foo = 'bar';
php > var_dump((array) $std);
php shell code:1:
array(1) {
  'foo' =>
  string(3) "bar"
}
```

**Comment by NiMeDia** [comment]
@bshaffer before just closing this one could you please at least read the conversation -> braindead casting will not work for nestet objects. It will cause bugs in the wild and it would be good if the project itself would handle the casting properly and well tested. It would be nice if you instead just accept the pull request (including tests) which was done with care by another user of this project. Thanks a lot...

For all others following a google search:
**The suggested solution will NOT work with nested objects.**

**Comment by bshaffer** [comment]
@NiMeDia you can cast any nested `stdClass` as an array in the same way.

In the next major release of this library we will use `array` instead of `stdClass`, but in the meantime this functionality is not going to change.

**Pull request closed without merging**
