### PR TITLE
Add in support for late static binding

### PR DESCRIPTION
**Pull request by chappy84**
Enables developers to extend the class and override variables / methods if they so require.

### CODE REVIEW

**Comment by chappy84** [comment]
I signed it!

**Comment by chappy84** [comment]
I signed it!

**Comment by robertdimarco** [comment]
@chappy84 Any chance you'd have time to take a peek at these merge conflicts? I'll merge asap after that; this looks good to me!

**Comment by chappy84** [comment]
@robertdimarco Should be all sorted now :)

**Comment by chappy84** [comment]
@robertdimarco Should be all sorted now :)

**Comment by chappy84** [comment]
@robertdimarco Thanks for merging :)
I was wondering if there were plans to tag a new version so those using composer can start updating?

**Comment by robertdimarco** [comment]
@chappy84 Shipped! Thanks for all of your help on this release. =) 🚢

**Comment by chappy84** [comment]
Thanks @robertdimarco, much appreciated!

**Pull request merged**
