### PR TITLE
chore: add phpstan for static analysis

### PR DESCRIPTION
**Pull request by bshaffer**
implements #404

### CODE REVIEW

**Comment by pabloelcolombiano** [comment]
This is a nice move.

The checks are performed on the lowest level. As described [here](https://phpstan.org/config-reference), we could aim at a level of at least 7.

**Comment by bshaffer** [comment]
> This is a nice move.
> 
> The checks are performed on the lowest level. As described [here](https://phpstan.org/config-reference), we could aim at a level of at least 7.

@pabloelcolombiano woops, your comment popped up just as I merged.

I decided to use PHP 8.0 because without it, I was getting the following error:

```
  Line   Key.php                                                              
 ------ --------------------------------------------------------------------- 
  24     Class OpenSSLAsymmetricKey not found.                                
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
 ------ --------------------------------------------------------------------- 
```

Do you know how this would be resolved on PHP 7.1? If so, I'm happy to move it.

**Comment by pabloelcolombiano** [comment]
I mean level 7 of PHPStan, as described in the docs, not the PHP version.

**Comment by pabloelcolombiano** [comment]
Here is an example of how I use PHPStan for the [fixture factories](https://github.com/vierge-noire/cakephp-fixture-factories/blob/main/phpstan.neon).

**Comment by bshaffer** [comment]
done in https://github.com/firebase/php-jwt/pull/407!

**Pull request merged**
