### PR TITLE
Use json_encode with option JSON_UNESCAPED_SLASHES

### PR DESCRIPTION
**Pull request by dolmen**
When encoding JSON, use option JSON_UNESCAPED_SLASHES which allows to disable a non-standard unnecessary over-encoding of `/` as `\/` by [`json_encode`](https://www.php.net/manual/fr/function.json-encode.php).

This option of json_encode is available on PHP 5.4+.

### CODE REVIEW

**Comment by dolmen** [comment]
Why label `v6.0`?

**Comment by bshaffer** [comment]
Because it will break backwards compatibility and drop a supported version of PHP, semantic versioning requires that we tag it for a new major version.

**Comment by Krisell** [comment]
That is not necessarily the case: https://medium.com/@sampart/semantic-versioning-when-you-change-the-required-programming-language-version-16a3a3555c95

However I agree that it's best to include such updates in a nearby major release if there is one.

**Comment by bshaffer** [comment]
@Krisell I meant changing the behavior of `json_encode` is what breaks backwards compatibility!

**Comment by dolmen** [comment]
@bshaffer Why did you merged unrelated commits into my branch?

**Comment by bshaffer** [comment]
> @bshaffer Why did you merged unrelated commits into my branch?

I updated your branch with changes made to master so that your PR is up to date.

**Comment by dolmen** [comment]
Rebased on top of `master`.

**Comment by bshaffer** [comment]
@dolmen it's been a while, but could you resubmit this branch to the `v6.0` branch? If not, I can merge it into `master`, but I'd prefer to have all `v6.0` changes separate if possible. Thank you!

**Comment by dolmen** [comment]
@bshaffer Have you heard about [`git cherry-pick`](https://git-scm.com/docs/git-cherry-pick)?

**Comment by bshaffer** [comment]
@dolmen yes i have. Why do you ask?

**Pull request closed without merging**
