### PR TITLE
add 7.4 to travis

### PR DESCRIPTION
**Pull request by vitaliytv**
remove old PHP versions

### CODE REVIEW

**Comment by Krisell** [comment]
I think this is reasonable since previous versions has reached EOL. However `composer.json` specifies `>=5.3.0` so that should probably be updated as well, and this need to be released as a new major version.

**Comment by vitaliytv** [comment]
> I think this is reasonable since previous versions has reached EOL. However `composer.json` specifies `>=5.3.0` so that should probably be updated as well, and this need to be released as a new major version.

Is php in composer.json  the minimum requirements for this package (not maintained and tested)?

**Comment by Krisell** [comment]
I believe so, yes. See the comment here: https://github.com/firebase/php-jwt/pull/261

**Comment by vitaliytv** [comment]
> I believe so, yes. See the comment here: #261

@Krisell  upd composer to 5.4

**Comment by Krisell** [comment]
Why specifically 5.4? I agree that the required version is not necessarily the same as the lowest version under test, but perhaps it should be?

**Comment by vitaliytv** [comment]
> Why specifically 5.4? I agree that the required version is not necessarily the same as the lowest version under test, but perhaps it should be?

5.4 because #261

upd to minimum in travis (7.2)

**Comment by bshaffer** [comment]
This should just be added to #261.

**Pull request closed without merging**
